#!/usr/bin/env bash

set -Eeuxo pipefail

    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-14.2-postgis-3.2.1' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-14.2-postgis-3.2.1,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:14.2-postgis-3.2.1' \
      --file 14/bullseye/postgis-3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-13.6-postgis-3.2.1' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-13.6-postgis-3.2.1,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:13.6-postgis-3.2.1' \
      --file 13/bullseye/postgis-3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-12.10-postgis-3.2.1' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-12.10-postgis-3.2.1,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:12.10-postgis-3.2.1' \
      --file 12/bullseye/postgis-3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-11.15-bullseye-postgis-3.2.1' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-11.15-bullseye-postgis-3.2.1,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:11.15-bullseye-postgis-3.2.1' \
      --file 11/bullseye/postgis-3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-11.15-postgis-3.2.1' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-11.15-postgis-3.2.1,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:11.15-postgis-3.2.1' \
      --file 11/stretch/postgis-3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-11.15-postgis-2.5.5' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-11.15-postgis-2.5.5,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:11.15-postgis-2.5.5' \
      --file 11/stretch/postgis-2.5/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-10.20-bullseye-postgis-3.2.1' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-10.20-bullseye-postgis-3.2.1,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:10.20-bullseye-postgis-3.2.1' \
      --file 10/bullseye/postgis-3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-10.20-postgis-3.2.1' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-10.20-postgis-3.2.1,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:10.20-postgis-3.2.1' \
      --file 10/stretch/postgis-3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-10.20-postgis-2.5.5' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-10.20-postgis-2.5.5,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:10.20-postgis-2.5.5' \
      --file 10/stretch/postgis-2.5/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=nickblah/postgis:build-cache-10.20-postgis-2.4.4' \
      --cache-to 'type=registry,ref=nickblah/postgis:build-cache-10.20-postgis-2.4.4,mode=max' \
      --tag 'localhost:5000/nickblah/postgis:10.20-postgis-2.4.4' \
      --file 10/stretch/postgis-2.4/Dockerfile \
      .
