#!/usr/bin/env bash

set -Eeuo pipefail

    printf "12.1-postgis-3.0.0: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:12.1-postgis-3.0.0 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "12.1-postgis-2.5.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:12.1-postgis-2.5.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "11.6-postgis-3.0.0: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:11.6-postgis-3.0.0 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "11.6-postgis-2.5.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:11.6-postgis-2.5.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "10.11-postgis-3.0.0: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:10.11-postgis-3.0.0 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "10.11-postgis-2.5.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:10.11-postgis-2.5.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "10.11-postgis-2.4.4: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:10.11-postgis-2.4.4 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.6.16-postgis-3.0.0: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.6.16-postgis-3.0.0 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.6.16-postgis-2.5.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.6.16-postgis-2.5.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.6.16-postgis-2.4.4: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.6.16-postgis-2.4.4 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.6.16-postgis-2.3.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.6.16-postgis-2.3.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.5.20-postgis-3.0.0: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.5.20-postgis-3.0.0 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.5.20-postgis-2.5.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.5.20-postgis-2.5.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.5.20-postgis-2.4.4: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.5.20-postgis-2.4.4 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.5.20-postgis-2.3.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.5.20-postgis-2.3.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.4.25-postgis-2.5.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.4.25-postgis-2.5.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.4.25-postgis-2.4.4: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.4.25-postgis-2.4.4 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

    printf "9.4.25-postgis-2.3.3: "
    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh --rm nickblah/postgis:9.4.25-postgis-2.3.3 2>&1 || true)
    if [[ $output =~ "PostGIS Tests: Error" ]]; then
      echo "Error"
      echo $output
      echo
    elif [[ $output =~ "PostGIS Tests: OK" ]]; then
      echo "OK"
    else
      echo "Unexpected Error"
      echo $output
      echo
    fi

