name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "39 3 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Update Dockerfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./update-ci
      - name: Docker Build
        run: ./docker-build
      - name: Docker Registry Login
        run: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: ./docker-push
